[11기 Tekiter] 스텝1 에스프레소 메뉴 관리
blackcoffee-study/moonbucks-menu pull request #23
Opened 2021-10-11 18:17 UTC by Tekiter

## 특징
- 상태와 메인 로직을 한 곳에 따로 정의합니다.
- 상태 기반으로 뷰를 그립니다. DOM을 메인 로직에서 직접 접근하지 않습니다.
- html 파일에서 자체 템플릿 문법을 사용합니다.
- Virtual DOM 비스무리하게 만들었지만, 아직은 실제 DOM 비교해서 적용하지 않고 그냥 둘을 바꿔치기 합니다.

## 요구사항 진행률
-   [x] 에스프레소 메뉴에 새로운 메뉴를 확인 버튼 또는 엔터키 입력으로 추가한다.
    -   [x] 메뉴가 추가되고 나면, input은 빈 값으로 초기화한다.
    -   [x] 사용자 입력값이 빈 값이라면 추가되지 않는다.
-   [x] 메뉴의 수정 버튼을 눌러 메뉴 이름 수정할 수 있다.
    -   [x] 메뉴 수정시 브라우저에서 제공하는 `prompt` 인터페이스를 활용한다.
-   [x] 메뉴 삭제 버튼을 이용하여 메뉴 삭제할 수 있다.
    -   [x] 메뉴 수정시 브라우저에서 제공하는 `confirm` 인터페이스를 활용한다.
-   [x] 총 메뉴 갯수를 count하여 상단에 보여준다.

## 소감
- 템플릿을 해석하고 채워넣는 코드가 만드는게 생각보다 복잡했습니다... ㅠㅠ
- 코드를 나름 클래스화 시켜봤는데, 여전히 너무 지저분한 것 같습니다.

2021-10-12 11:29 UTC, onethegarden reviewed
필요없는 주석 없이 깔끔한 코드 많이 배우고 갑니다  ☺️

2021-10-12 11:48 UTC, onethegarden requested changes

2021-10-12 11:48 UTC, onethegarden commented on src/js/index.js
> +        serial: 0,
`count`, `serial` 도 위에 작성하신 것처럼 menu를 나타내고 있으니까 `menuCount`, `menuSerial`로 통일하는게 어떨까요?

2021-10-12 12:28 UTC, onethegarden reviewed
virtual dom을 구현하려고 하신 부분이 인상깊었습니다 !

2021-10-12 12:43 UTC, nerdyinu reviewed
안녕하세요! 코드 잘 봤습니다. 객체지향에 대한 개념이 부족해서 작성해주신 코드의 의도를 파악하기가 좀 힘이 드네요. 혹시 작성하신 코드를 이해하는데 도움이 될만한 개념이나 패턴 등의 키워드를 알려주실 수 있을까요?

2021-10-13 02:37 UTC, SINHOLEE commented on src/js/xapp/index.js
> +        for (const key in handlers) {
for in 보다는 for of가 더 모던한 방식이라고 하네요 ㅎㅎ
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/for...of

아실 수도 있지만 `for (const [key, handler] of Object.entries(handlers)){this.methods[key] = handler}` 처럼 사용하시면 됩니다.

2021-10-13 02:37 UTC, SINHOLEE commented on src/js/xapp/util.js
> +export function getProp(obj, path = []) {
loadash의 get과 같은 역할을 하는 친구였네요!!  제기준에서는 주석에 이 함수가 어떤 동작을 하는지 간단한 설명과 예시를 주셨으면 조금 더 이해하기 편했을거라고 생각해요!!

중첩된 obj에서 해당 path에 해당하는 값을 바로 반환하는 함수
ex) obj = {a:1, b:2, c:{d:3}}, path = ['c','d'] // 3 

이런식으로요!

2021-10-15 09:42 UTC, Tekiter commented
> 안녕하세요! 코드 잘 봤습니다. 객체지향에 대한 개념이 부족해서 작성해주신 코드의 의도를 파악하기가 좀 힘이 드네요. 혹시 작성하신 코드를 이해하는데 도움이 될만한 개념이나 패턴 등의 키워드를 알려주실 수 있을까요?

[웹 컴포넌트 상태 관리](https://junilhwang.github.io/TIL/Javascript/Design/Vanilla-JS-Store/) 와 [Virtual DOM](https://junilhwang.github.io/TIL/Javascript/Design/Vanilla-JS-Virtual-DOM) 내용을 참고해 보시면 될 것 같아요!

2021-10-15 11:02 UTC, Tekiter commented on src/js/xapp/index.js
> +        for (const key in handlers) {
해당 문서에서

> for...in 루프는 객체의 모든 열거가능한 속성에 대해 반복합니다. 
> for...of 구문은 컬렉션 전용입니다. 모든 객체보다는, [Symbol.iterator] 속성이 있는 모든 컬렉션 요소에 대해 이 방식으로 반복합니다.

이런 구절이 있는데, 컬렉션이 아닌 객체의 모든 속성에 대해 반복해야 하는 현재 상황에는 for ... in 도 적절하지 않을까요?

2021-10-15 11:04 UTC, Tekiter commented on src/js/xapp/util.js
> +export function getProp(obj, path = []) {
좋은 생각이네요. 아니면 함수 이름을 getPropertyRecursivly 나 getNestedProperty 같이 변경하는 것도 좋은 것 같습니다.

2021-10-15 12:45 UTC, SINHOLEE commented on src/js/xapp/index.js
> +        for (const key in handlers) {
말씀하신 부분 충분히 공감합니다. 제가 개인적으로  더 최신스펙=== 모던 === 올바르다. 라고 가볍게 받아들이고 있었는데 덕분에 발상의 전환을 하게 되었어요.
 for of 구문은 일부 ie버전에서 사용불가하다고 하니 호환성 부분에서는 오히려 for in 구문에 더 알맞겠군요.(바벨 미사용 시)
상황에 따라 적절한 문법사용의 중요성을 다시한번 생각하게 되는 코멘트였습니다. 감사합니다 ㅎㅎ

2021-10-16 06:32 UTC, merged