[11기 small-j] 스텝1 에스프레소 메뉴 관리
blackcoffee-study/moonbucks-menu pull request #27
Opened 2021-10-12 05:01 UTC by small-j

## 요구사항 수행
- [ ]  에스프레소 메뉴에 새로운 메뉴를 확인 버튼 또는 엔터키 입력으로 추가한다.
- [ ] 메뉴가 추가되고 나면, input은 빈 값으로 초기화한다.
- [ ]  사용자 입력값이 빈 값이라면 추가되지 않는다.
- [ ] 메뉴의 수정 버튼을 눌러 메뉴 이름 수정할 수 있다.
- [ ] 메뉴 수정시 브라우저에서 제공하는 prompt 인터페이스를 활용한다.
- [ ] 메뉴 삭제 버튼을 이용하여 메뉴 삭제할 수 있다.
- [ ] 메뉴 삭제시 브라우저에서 제공하는 confirm 인터페이스를 활용한다.
- [ ] 총 메뉴 갯수를 count하여 상단에 보여준다.

## 고민 중인 부분
- 일단 지금은 document 객체에서 3개의 요소를 받아와 로직을 처리하는 app.js로 넘겨주고 있는데 이를 하나의 요소만 받아와 다른 요소에 효과적으로 접근하는 방법.
- 컴포넌트를 메뉴리스트와 메뉴리스트 count 하는 부분으로 나눠놓았는데 이렇게 나눈 형태가 적절한지.
- 각 컴포넌트에서 의존성을 가지지 않고 독립적으로 돌아가는 것이 맞는지.

2021-10-12 11:50 UTC, mintplo requested changes
2개의 코멘트 달았습니다 👍🏼

2021-10-12 11:50 UTC, mintplo commented on src/js/pages/app.js
> +            const newMenu = e.target.previousElementSibling;
[제안]
`newMenu`가 새로운 메뉴를 입력하는 Input element라고 이해했는데요. `newMenuInput`으로 조금 더 명확하게 변수의 이름을 지어주면 어떨지 제안해봐요 👍🏼

2021-10-12 11:50 UTC, mintplo commented on src/js/pages/app.js
> +    setEvent() {
[제안]
`App` 내 `setEvent`가 어떤 역할을 하는지 이름만 봤을 때는 알기 어려운 것 같아요.

`setEventListener` 또는 `bindEventListener` 같이 조금 더 명확하게 네이밍을 해보는 건 어떨까요?

2021-10-12 11:56 UTC, ChangSubKwak commented on src/js/pages/app.js
> +            confirm('정말 삭제하시겠습니까?');
onMenuClick 이 아닌 clickMenuItem은 어떤지 생각을 듣고 싶어요.
그리고 action에 따른 기능 수행 부분을 수정과 삭제 기능을 나누어서 updateMenuItem, deleteMenuItem 로 작성하는 것도 하나의 방법이라고 생각해요. 또 하나의 이유는 메뉴는 에스프레소, 프라푸치노, 블렌디드, 티바나, 디저트의 중 하나이고 에스프레소 메뉴의 MenuItem이 아메리카노, 카페라떼, 이렇게 될 것 같은 생각이 들어요.

2021-10-12 11:56 UTC, ChangSubKwak commented on src/js/pages/menuCount.js
> +export default class MenuCount {
위와 같은 이유로 MenuCount도 MenuItemCount로 하는 것은 어떨지 궁금해요

2021-10-12 12:09 UTC, ChangSubKwak commented on src/js/pages/app.js
> +        if(typeof(result) === 'string') {
if 다음에 공백이 들어가는 것이 보통 javascript code convention(K&R - https://en.wikipedia.org/wiki/Indentation_style#K.26R_style) 중 하나로 알고 있어요. 
이런 건 prettier 같은 것을 사용하면 좋을 것 같아요.

2021-10-12 12:30 UTC, ChangSubKwak reviewed
개인적으로 기능별로 class를 선언하여 파일을 나눈 부분이 깔끔해서 좋았습니다.

2021-10-12 12:30 UTC, ChangSubKwak commented on src/js/index.js
> +    document.querySelector('.menu-count'),
document.querySelector 두 번 이상 쓰이면 관용적으로 쓰이는 $나 원하시는 변수명으로 해서 선언해두고 사용하시면 좋을 것 같아요.

2021-10-12 12:30 UTC, ChangSubKwak commented on src/js/index.js
> +    );
new line을 추가해주시면 될 것 같습니다.

2021-10-16 06:33 UTC, merged

2021-10-16 16:50 UTC, small-j commented on src/js/pages/app.js
> +            const newMenu = e.target.previousElementSibling;
명확하게 하는 것이 좋을 것 같습니다! 좋은 제안 감사드립니다

2021-10-16 16:51 UTC, small-j commented on src/js/pages/app.js
> +    setEvent() {
좋은 제안 너무 감사드립니다! 이렇게 개선해 나가는 것이겠지요!

2021-10-16 16:55 UTC, small-j commented on src/js/pages/app.js
> +        if(typeof(result) === 'string') {
오 좋은 조언 감사드립니다!

2021-10-16 16:56 UTC, small-j commented on src/js/index.js
> +    document.querySelector('.menu-count'),
넵! 이번에 처음 알게되었네요 분명 중복되는 코드는 줄이라고 항상 들어왔는데 왜 저렇게 짠 것인지 반성해야겠습니다

2021-10-16 17:01 UTC, small-j commented on src/js/pages/menuCount.js
> +export default class MenuCount {
좋은 의견입니다! MenuItemCounter 라고 한다면 더 좋을 것 같네요. 이렇게 갑자기 제 코드의 개선점을 더 찾아버렸습니닿ㅎ

2021-10-16 17:02 UTC, small-j commented on src/js/pages/app.js
> +            confirm('정말 삭제하시겠습니까?');
동사 뒤에 명사를 붙이던 규칙을 지키려고 하다보니 저렇게 이름을 지었습니다! 혹시 제안해주신 이름에서 click을 동사로 생각하신 것인지요?? 좋은 의견 너무 감사드립니다.
기능 수행 부분은 나누는 방향으로 개선해보도록 하겠습니다! 
마지막 부분에서 설명해주신 부분은 제가 이해한 바로는 각 메뉴가 메뉴 안의 메뉴이니 Item이라고 변경하라는 말씀으로 받아들였는데 좋은 의견이라고 생각합니다! 감사합니다

2021-10-19 00:34 UTC, ChangSubKwak commented on src/js/pages/app.js
> +            confirm('정말 삭제하시겠습니까?');
넵, 맞아요. ^^ click을 동사로 생각해서 말씀드린 것 입니다.