[14기 민오] step2 요구사항 - 상태 관리로 메뉴 관리하기
blackcoffee-study/moonbucks-menu pull request #280
Opened 2022-07-20 02:35 UTC by dhrod0325

## 요구사항 목록

- [x] [localStorage](https://developer.mozilla.org/ko/docs/Web/API/Window/localStorage)에 데이터를 저장하여 새로고침해도 데이터가 남아있게 한다.
- [x] 에스프레소, 프라푸치노, 블렌디드, 티바나, 디저트 각각의 종류별로 메뉴판을 관리할 수 있게 만든다.
  - [x] 페이지에 최초로 접근할 때는 에스프레소 메뉴가 먼저 보이게 한다.
- [x] 품절 상태인 경우를 보여줄 수 있게, 품절 버튼을 추가하고 `sold-out` class를 추가하여 상태를 변경한다.
- [x] 품절 상태 메뉴의 마크업

## 어려웠던 점
- 늘 class로만 작업하다가 함수로 로직을 작성 하려고 하니 어렵네요... 점점 코드가 스파게티가 되어 가는 것 같아요.
- custom 이벤트 방식은 사용할때 마다 느끼는거지만 이벤트가 늘어날수록 관리가 어려워 지는 것 같아요!

2022-07-25 02:28 UTC, yeomgahui requested changes
코드 잘 봤습니다!  궁금한 질문 몇개 남겼어요.. (많지 않아요 ㅎㅎ)  
시간 날때 코드 설명 해주시면 너무 감사할것같아요 ㅎㅎ

2022-07-25 02:28 UTC, yeomgahui commented on src/js/components/MenuCategory.js
> +  setTimeout(() => $buttons[0].click());
여기서 setTimeout을 쓰신 이유가 있나요?

2022-07-25 02:28 UTC, yeomgahui commented on src/js/components/MenuCategory.js
> +import { $all, dispatchCustomEvent } from "../util";
이렇게 import해오는 방식은 제가 처음 봐서 그런데 '../util/index.js' 가 아니라 '../util'이렇게 import해왔을때의 차이가 궁금해요..!!

2022-07-25 15:57 UTC, dhrod0325 reviewed
리뷰 감사해요 팝콘님! 👍

2022-07-25 15:57 UTC, dhrod0325 commented on src/js/components/MenuCategory.js
> +import { $all, dispatchCustomEvent } from "../util";
별 차이 없어요! 만약에 `util/contents/test.js` 이런식으로 되있어도 index에서 export했다면 그때도 `/util`로 할 수 있다는 정도?! 😀

2022-07-25 15:57 UTC, dhrod0325 commented on src/js/components/MenuCategory.js
> +  setTimeout(() => $buttons[0].click());
저는 `customEvent`로 상태에 대한 변경을 확인하고 있는데 `setTimeout`을 선언하지 않으면 `customEvent`들이 **bind되기 전에 click함수가 먼저 호출**되어서 제대로 동작을 안해서 `setTimeout`을 사용했어요!

2022-07-26 13:50 UTC, merged

2022-07-28 11:31 UTC, zwonlala commented on src/js/components/MenuListItem.js
> +    }
class 리스트에 추가하거나 제거하는 로직을 위와 같이 if-else 로 분기해서 하는 방법도 있지만

toggle() 메소드사용하면 한줄로 구현 가능합니다

https://developer.mozilla.org/ko/docs/Web/API/Element/classList#%EB%A9%94%EC%84%9C%EB%93%9C

2022-07-28 11:31 UTC, zwonlala commented on src/js/components/MenuListItem.js
> +    }
```suggestion
    $menuName.classList.toggle(soldoutClassName, check === "true");
```

2022-07-28 11:31 UTC, zwonlala commented on src/js/components/MenuListItem.js
> +  function toggleSoldout(check) {
check 변수를 boolean 이 아닌 문자열로 관리하는 이유가 있나요? 🤔